### ISSUE TITLE
增加webpack构建版本

### ISSUE THREAD

**Issue by LingyuCoder** [react-melon/melon#37]
目前react项目广泛使用webpack构建，想要一起使用这个edp构建的组件库比较麻烦，简易增加webpack构建版本，并发布到npm上

另外，bower已死

**Comment by jinzhubaofu** [comment]
现在的这个构建方案是有我们内部的历史原因的。我们内部一直都是 edp，对开源小伙伴这样很不友好。我们会尽快加上这个功能。

**Comment by jinzhubaofu** [comment]
@LingyuCoder 

抱歉我们之前没有对于 webpack 给出相关的指南。现在我们已经添加好了，在[这里](https://github.com/react-melon/melon#如何在-webpack-中使用-melon)。另外，还提供了一个 wepack 的 [demo repo](https://github.com/Sheetaa/melon-webpack-demo)。

欢迎试用。
