### ISSUE TITLE
[ColorPicker]颜色选择器坐标异常

### ISSUE THREAD

**Issue by shianqi** [react-melon/melon#75]
当滚动条不在最上方时，颜色选择器坐标异常。
感觉是坐标选错了，应该使用文档坐标，而不是窗口坐标。

**Comment by shianqi** [comment]
win 10
chrome(60.0.3112.101)
![u 8 wk6 ydn2sv4ym ktry](https://user-images.githubusercontent.com/13609675/29820242-7558bd4e-8cf6-11e7-8762-0d293f0f4ec0.png)
![62 l r 0t41ikz dhz13c](https://user-images.githubusercontent.com/13609675/29820248-7abf3790-8cf6-11e7-8538-43ab592d7189.png)

**Comment by jinzhubaofu** [comment]
@shianqi 已经修复，发布 melon-colorpicker@1.2.2，请更新后再试试看

具体的 issue [melon-colorpicker issue 7](https://github.com/react-melon/melon-colorpicker/issues/7)
